[STANDARD_PARAMETERS.x]
name = "x"
description = "The x position"
value = 0
unit = "mas"
min = -30
max = 30

[STANDARD_PARAMETERS.y]
name = "y"
description = "The y position"
value = 0
unit = "mas"
min = -30
max = 30

[STANDARD_PARAMETERS.f]
name = "f"
description = "The flux"
value = 0
unit = "Jy"
min = 0
max = 10
smooth = true

[STANDARD_PARAMETERS.lnf]
name = "lnf"
description = "The error correction term"
unit = "one"
min = -10
max = 1
free = false
shared = true

[STANDARD_PARAMETERS.fr]
name = "fr"
description = "The flux ratio"
value = 1
unit = "one"
min = 0
max = 1

[STANDARD_PARAMETERS.cinc]
name = "cinc"
description = "The cosine of the inclination"
value = 1
unit = "one"
min = 0
max = 1

[STANDARD_PARAMETERS.pa]
name = "pa"
description = "The major-axis position angle"
value = 0
unit = "deg"
min = -180
max = 180

[STANDARD_PARAMETERS.pixel_size]
name = "pixel_size"
description = "The pixel size"
value = 1
unit = "mas"
min = 0
max = 100

[STANDARD_PARAMETERS.dim]
name = "dim"
description = "The pixel dimension"
value = 128
unit = "one"
dtype = "int"

[STANDARD_PARAMETERS.exp]
name = "exponent"
description = "An exponent"
value = 1
unit = "one"
min = 0
max = 1
free = true

[STANDARD_PARAMETERS.wl]
name = "wl"
description = "The wavelength"
value = 0
unit = "um"

[STANDARD_PARAMETERS.fov]
name = "fov"
value = 0
min = 0
max = 100
description = "The field of view"
unit = "mas"

[STANDARD_PARAMETERS.rho]
name = "rho"
description = "The modulation amplitude"
value = 0
unit = "one"
min = 0
max = 1

[STANDARD_PARAMETERS.theta]
name = "theta"
description = "The major-axis modulation angle"
value = 0
unit = "deg"
min = -180
max = 180

[STANDARD_PARAMETERS.width]
name = "width"
description = "The width"
value = 0
unit = "mas"
min = 0
max = 300
free = true

[STANDARD_PARAMETERS.r0]
name = "r0"
description = "Reference radius"
value = 1
unit = "au"

[STANDARD_PARAMETERS.rin]
name = "rin"
value = 0
unit = "mas"
min = 0
max = 50
description = "The inner radius"
free = true

[STANDARD_PARAMETERS.rout]
name = "rout"
description = "The outer radius"
min = 0
unit = "mas"
max = 300
value = 300

[STANDARD_PARAMETERS.temp0]
name = "temp0"
description = "The temperature at a reference radius"
value = 0
unit = "K"
min = 0
max = 3000
free = true

[STANDARD_PARAMETERS.tempc]
name = "tempc"
description = "The characteristic temperature"
value = 0
unit = "K"
min = 0
max = 3000
free = true

[STANDARD_PARAMETERS.q]
name = "q"
value = 0
min = 0
max = 1
unit = "one"
description = "The power-law exponent for a temperature profile"
free = true

[STANDARD_PARAMETERS.p]
name = "p"
description = "The power-law exponent for a dust surface density profile"
value = 0
unit = "one"
min = 0
max = 1
free = true

[STANDARD_PARAMETERS.sigma0]
name = "sigma0"
description = "The surface density at a reference radius"
value = 0
unit = "g/cm^2"
min = 0
max = 0.01
free = true

[STANDARD_PARAMETERS.kappa_abs]
name = "kappa_abs"
description = "The dust mass absorption coefficient"
value = 0
unit = "cm^2/g"
smooth = true

[STANDARD_PARAMETERS.kappa_cont]
name = "kappa_cont"
description = "The continuum dust mass absorption coefficient"
value = 0
unit = "cm^2/g"
smooth = true

[STANDARD_PARAMETERS.weight_cont]
name = "weight_cont"
description = "The mass fraction of continuum vs. silicate"
value = 0
unit = "pct"
min = 0
max = 100
free = true

[STANDARD_PARAMETERS.pah]
name = "pah"
description = "The flux curve of the PAHs"
value = 0
unit = "Jy"

[STANDARD_PARAMETERS.scale_pah]
name = "scale_pah"
description = "The mass fraction for the PAHs"
value = 0
unit = "one"
free = true

[STANDARD_PARAMETERS.dist]
name = "dist"
description = "The Distance"
value = 0
unit = "pc"
min = 0
max = 1000

[STANDARD_PARAMETERS.eff_temp]
name = "eff_temp"
description = "The star's effective temperature"
value = 0
unit = "K"
min = 0
max = 30000

[STANDARD_PARAMETERS.eff_radius]
name = "eff_radius"
description = "The stellar radius"
value = 0
unit = "Rsun"
min = 0
max = 10
