name: CI
on:
  pull_request:
    paths-ignore:
    - docs/**
    - README.md
  push:
    branches:
    - analytical_modulation

jobs:
  tests:
    strategy:
      matrix:
        os:
        - macos-latest
        python-version:
        - '3.11'

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup package
      run: |
        python -m pip install --upgrade pip
        python -m pip install ".[dev]"
    - name: Run tests
      run: |
        cd tests/
        pytest --color=yes
